In [8]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
'''cpu has 3 parts
1.control Unit
2.memory units
3.Arithmatic/Logic unit

Conditional Statement:
if
if else
if elif else
nested if
'''

In [2]:
if True:
    print("Data Science")

Data Science


In [5]:
if False:
    print("Data Science")
print('bye for now')

bye for now


In [7]:
if True:
    print("Data Science")
else:
    print('bye for now')

Data Science


In [6]:
if False:
    print("Data Science")
else:
    print('bye for now')

bye for now


In [8]:
number = 4
if(number % 2 == 0):
    print("Even Number")
else:
    print("Odd number")
    

Even Number


In [11]:
number = 5
if(number % 2 == 1):
    print("Odd Number")
else:
    print("Even number")

Odd Number


In [1]:
x = 4
r = x % 2
if r == 0:
    print("Even Number")

Even Number


In [ ]:
#gfg examples

In [ ]:
#Loop
#While and nested While Loop
i=4
while i <= 5:
    print("Data Science")
    i = i + 1

Data Science
Data Science


In [12]:
i=1
while i <= 5:
    print("Data Science :", i)
    i = i + 1

Data Science : 1
Data Science : 2
Data Science : 3
Data Science : 4
Data Science : 5


In [11]:
i=5
while i >= 1:
    print("Data Science :", i)
    i = i - 1

Data Science : 5
Data Science : 4
Data Science : 3
Data Science : 2
Data Science : 1


In [20]:
i=1
while i <= 5:
    print("Data Science ")
    j = 1
    while j <= 4:
        print("technology")
        j = j + 1
    i = i + 1
    print()

Data Science 
technology
technology
technology
technology

Data Science 
technology
technology
technology
technology

Data Science 
technology
technology
technology
technology

Data Science 
technology
technology
technology
technology

Data Science 
technology
technology
technology
technology



In [18]:
i=1
while i <= 5:
    print("Data Science ", end ="")
    j = 1
    while j <= 4:
        print("technology ", end="")
        j = j + 1
    i = i + 1
    print()

Data Science technology technology technology technology 
Data Science technology technology technology technology 
Data Science technology technology technology technology 
Data Science technology technology technology technology 
Data Science technology technology technology technology 


In [21]:
year = int(input("Enter a year: "))

if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
 print("Leap Year")
else:
 print("Not a Leap Year") 

Not a Leap Year


In [2]:
i =1 
while i <= 5:
    print("data Science")
    i = i + 1

data Science
data Science
data Science
data Science
data Science


In [ ]:
i = 1
while i <= 2:
    j = 0
    while j <= 2:
        print(i*j, end="")
        j+=1
    print()
    i += 1

012
024


In [ ]:
i = 1
while i <= 4:
    j = 0
    while j <= 3:
        print(i*j, end="")
        j+=1
    print()
    i += 1
    #f8 to debug the code

0123
0246
0369
04812


In [ ]:
#while loop you can when you have some condition
#for loop you can when you datatypes and datastructure -- Python Sequences

In [7]:
name ='shravani'
for i in name:
    print(i)

s
h
r
a
v
a
n
i


In [8]:
name1 = [1,2,3,'hello']
for i in name1:
    print(i)

1
2
3
hello


In [9]:
for i in range(5):
    print(i)

0
1
2
3
4


In [10]:
for i in range(1,10,3):
    print(i)

1
4
7


In [12]:
for i in range(1,51):
    if i % 5 == 0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [14]:
for i in range(1,30):
    if i % 5 != 0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29


In [ ]:
#break - jumps out of the function/loop
#continue - skip the particular position and contiue the loop
#pass - use abstraction (pass the error)

In [17]:
for i in range(1,11):
    if  i == 8:
        break
    print(i)

1
2
3
4
5
6
7


In [18]:
for i in range(1,11):
    if  i == 8:
        continue
    print(i)

1
2
3
4
5
6
7
9
10


In [ ]:
for i in range(1,11):
    pass #Pass error

In [ ]:
# in contineu loop won't be terminate but in break loop will terminate

In [21]:
x =  int(input("How many chocolate you want:?"))
i = 1
while i <= x:
    print("chocolate")
    i += 1

chocolate
chocolate
chocolate
chocolate
chocolate


In [22]:
avg = 5
x =  int(input("How many chocolate you want:?"))
i = 1
while i <= x:
    print("chocolate")
    i += 1

chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate
chocolate


In [24]:
avilable = 5
x =  int(input("How many chocolate you want:?"))
i = 1
while i <= x:
    if i > avilable: 
        print("Out of stock")
        break
    print("chocolate")  
    i += 1
print("bye for now")

chocolate
chocolate
chocolate
chocolate
chocolate
Out of stock
bye for now


In [25]:
for i in range(1,51):
    if i % 3 == 0:
        print(i)
print('end')

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [26]:
for i in range(1,51):
    if i % 3 == 0:
        continue
    print(i)
print('end')

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [27]:
for i in range(1,51):
    if i % 3 == 0 or i % 5 == 0:
        continue
    print(i)
print('end')

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [28]:
#For - Else
nums = [12,15,18,21,30,40]
for num in nums:
    if num % 5 == 0:
        print(num)

15
30
40


In [29]:
nums = [12,14,18,21,20,25]
for num in nums:
    if num % 5 == 0:
        print(num)
        break

20


In [31]:
nums = [7,14,18,21,23,27,4,7,9]
for num in nums:
    if num % 5 == 0:
        print(num)
else:
    print("number not found")

number not found


In [32]:
#Patterns in Python
for i in range(1,5):
    i = i+ 1
    print(" # # # #")
    

 # # # #
 # # # #
 # # # #
 # # # #


In [33]:
for i in range(1,5):
    if i <= 5:
     print(" # # # #")

 # # # #
 # # # #
 # # # #
 # # # #


In [34]:
for j in range(4):
    print('#')

#
#
#
#


In [35]:
for j in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [36]:
for j in range(4):
    print('#', end = " ")

# # # # 

In [37]:
for j in range(4):
    print('#', end=" ")
for j in range(4):
    print('#', end=" ")

# # # # # # # # 

In [38]:
for i in range(4):
    for j in range(4):
        print('#', end=" ")
    print()

# # # # 
# # # # 
# # # # 
# # # # 


In [39]:
for i in range(4):
    for j in range(i+1):
        print('#', end=" ")
    print()

# 
# # 
# # # 
# # # # 


In [43]:
for i in range(1,5):
    print('# ' * i)

# 
# # 
# # # 
# # # # 


In [28]:
for i in range(4):
    for j in range(4-i):
        print('#', end="  ")
    print()

#  #  #  #  
#  #  #  
#  #  
#  


In [47]:
num = 13
for i in range(2, num):
    if num % i == 0:
        print(num,"is not prime number")
        break
else:
    print(num,"is a Prime number")

13 is a Prime number


Array in Python

In [1]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

array('i', [10, 12, 13, 12, 15])


In [2]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [3]:
print(arr.dtype)

int64


In [4]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [5]:
print(arr.dtype)

float64


In [6]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [9]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [10]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

Right angle triangle Pattern

In [11]:
for i in range(1,6):
    print('*' * i)

*
**
***
****
*****


Inverted Right angle Triangle

In [12]:
for i in range(5,0,-1):
    print('*' *i)

*****
****
***
**
*


Pyramid Pattern

In [13]:
for i in range(1,6):
    print(''*(5-i)+ ' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 


Inverted Pyramid Pattern

In [14]:
for i in range(5,0,-1):
    print(''*(5-1)+' * '*(2*i-1))

 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


Diamond Pattern

In [15]:
for i in range(1,6):
    print(''*(5-i)+ ' * '*(2*i-1))
for i in range(4,0,-1):
    print(''*(5-i)+ ' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


Hallo Square Pattern

In [16]:
for i in range(5):
    for j in range(5):
        if i == 0 or i == 4 or j == 0 or j == 4:
            print('*', end="")
        else:
            print(' ', end='')
    print()

*****
*   *
*   *
*   *
*****


Full Square Pattern

In [18]:
for i in range(5):
    print(' * '*5)

 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 


Right Angle triangle(Number Pattern)

In [19]:
rows = 5
for i in range(1, rows + 1):
    for j in range(1, i+1):
        print(j, end =" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [23]:
rows = 5
for i in range(rows , 0, -1):
    for j in range(1, i+1):
        print(j, end =" ")
    print()

1 2 3 4 5 
1 2 3 4 
1 2 3 
1 2 
1 


Floyd's Triangle

In [25]:
num = 1
for i in range(1,6):
    for j in range(1, i+1):
        print(num, end=' ')
        num+=1
    print()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


Hallow Right Angle Triangle

In [27]:
for i in range(1,6):
    for j in range(1,i+1):
        if j == 1 or j == i  or i == 5:
            print('*', end = ' ')
        else:
            print(' ', end=' ')
    print()

* 
* * 
*   * 
*     * 
* * * * * 


Hallow Pyramid Pattern

In [30]:
for i in range(1,6):
    for j in range(5 - i):
        print(' ', end=' ')
    for j in range(2 * i - 1):
        if j == 0 or j == 2 * i - 2 or i == 5:
            print('*', end=' ')
        else:
            print(' ', end=' ')
    print()

        * 
      *   * 
    *       * 
  *           * 
* * * * * * * * * 


In [34]:
n = 5
for i in range(1, n + 1):
    for j in range(n - i):
        print(' ', end='')
    for j in range(2 * i - 1):
        if j == 0 or j == 2 * i - 2:
            print('*', end='')
        else:
            print(' ', end='')
    print()
    
for i in range(n - 1, 0, -1):
    for j in range(n - i):
        print(' ', end='')
    for j in range(2 * i - 1):
        if j == 0 or j == 2 * i - 2:
            print('*', end='')
        else:
            print(' ', end='')
    print()
    
    
    

    *
   * *
  *   *
 *     *
*       *
 *     *
  *   *
   * *
    *


In [35]:
n = 5
for i in range(1, n + 1):
    for j in range(n - i):
        print(' ', end='')
    for j in range(2 * i - 1):
        if j == 0 or j == 2 * i - 2:
            print(i, end='')
        else:
            print(' ', end='')
    print()
    
for i in range(n - 1, 0, -1):
    for j in range(n - i):
        print(' ', end='')
    for j in range(2 * i - 1):
        if j == 0 or j == 2 * i - 2:
            print(i, end='')
        else:
            print(' ', end='')
    print()
    

    1
   2 2
  3   3
 4     4
5       5
 4     4
  3   3
   2 2
    1


Full Start Pyramid

In [43]:
rows = 5

for i in range(1, rows + 1):
    print(" " * (rows - i), end=" ")
    print("* " * i)

     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


Inverted Full Star Pyramid

In [45]:
rows = 5

for i in range(rows, 0, -1):
    print(" " * (rows - i), end=" ")
    print("* " * i)

 * * * * * 
  * * * * 
   * * * 
    * * 
     * 


In [48]:
rows = 5

for i in range(1, rows + 1):
    print("* " * i)

rows = 5

for i in range(1, rows + 1):
    for j in range(1, i+1):
        print(j, end =" ")
    print()

* 
* * 
* * * 
* * * * 
* * * * * 
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [47]:
rows = 5
for i in range(1, rows + 1):
    for j in range(1, i+1):
        print(j, end =" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [58]:
rows = 5
for i in range(1, rows + 1):
    for j in range(i):
        print('*', end=' ')
    print()

rows = 5

for i in range(1, rows + 1): 
    for j in range(1, i + 1):
        print(j, end=" ")
    print()


* 
* * 
* * * 
* * * * 
* * * * * 
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [66]:
rows = 5 
for i in range(1, rows + 1):
    for j in range(rows - i):
        print(' ', end=' ')
    for j in range(1, i+1):
        print(j, end=' ')
    print()
    
rows = 5 
for i in range(1, rows + 1):
    for j in range(rows - i):
        print(' ', end=' ')
    for j in range(i):
        print('*', end=' ')
    print()

        1 
      1 2 
    1 2 3 
  1 2 3 4 
1 2 3 4 5 
        * 
      * * 
    * * * 
  * * * * 
* * * * * 
