In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
'''knn -> based on nearest naighbour we understod the class
Euclidian distance --> shortest distance amoung number
manhatten --> farther distance amoung number
cosine distance -> distance between text based and context of word

Imbalance Data 
A                     B 
95                    5
Majority class    Minority class

Down Sample -> 95 reduce to 70 (also called under sampling) -> Majority class
over sample -> 5 increase to 30 (also clled up sampling) -> maniority class

SMOTE(Synthetic Minority Oversampling Technique) 


knn classification -> based on majority of class  to classify the datapoints 

Outliers is impacting the knn model
outlier is not impacting the logistic regression beacause the 
sigmoid function --> probability function which adjust the outlier to 0-1

'''

In [2]:
df = pd.read_csv(r"C:\Users\omkar joshi\DATA SCIENCE\Databases\logit classification.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
x = df.iloc[:, [2,3]].values
y = df.iloc[:, -1].values

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20, random_state=0)

K- Nearest Neighbors

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[55  3]
 [ 1 21]]
0.95
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        58
           1       0.88      0.95      0.91        22

    accuracy                           0.95        80
   macro avg       0.93      0.95      0.94        80
weighted avg       0.95      0.95      0.95        80

0.91875
0.95


SVM

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[55  3]
 [ 1 21]]
0.95
              precision    recall  f1-score   support

           0       0.98      0.95      0.96        58
           1       0.88      0.95      0.91        22

    accuracy                           0.95        80
   macro avg       0.93      0.95      0.94        80
weighted avg       0.95      0.95      0.95        80

0.903125
0.95


Logistic Regression (Probability Algorithm )

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[57  1]
 [ 5 17]]
0.925
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        58
           1       0.94      0.77      0.85        22

    accuracy                           0.93        80
   macro avg       0.93      0.88      0.90        80
weighted avg       0.93      0.93      0.92        80

0.821875
0.925


Naive Bayes Algorithm (Probability Algorithm )

In [ ]:
'''Naive : 2 independent events p(A) & p(B) is called naive in naive bayes

conditional Probability :p(A/B) = p(A ^ B) / p(B) --> 
to find probability of A to be already occured B

bayes Theorem : p(A/B) = p(B/A) * p(A) / p(B)
types:

whye we study this real time :


Yfinance --> it is api it fetch all current market data and give it to u

'''