Logistic Regression

In [2]:
'''Logistic regression is a classification algorithm'''

'Logistic regression is a classification algorithm'

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv(r"C:\Users\omkar joshi\DATA SCIENCE\Databases\logit classification.csv")
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [6]:
x = df.iloc[:,[2,3]].values
y = df.iloc[:, -1].values

In [7]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
print(y.shape)
print(x.shape)

(400,)
(400, 2)


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.25, random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [12]:
x_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

In [13]:
x_test

array([[-0.80480212,  0.50496393],
       [-0.01254409, -0.5677824 ],
       [-0.30964085,  0.1570462 ],
       [-0.80480212,  0.27301877],
       [-0.30964085, -0.5677824 ],
       [-1.10189888, -1.43757673],
       [-0.70576986, -1.58254245],
       [-0.21060859,  2.15757314],
       [-1.99318916, -0.04590581],
       [ 0.8787462 , -0.77073441],
       [-0.80480212, -0.59677555],
       [-1.00286662, -0.42281668],
       [-0.11157634, -0.42281668],
       [ 0.08648817,  0.21503249],
       [-1.79512465,  0.47597078],
       [-0.60673761,  1.37475825],
       [-0.11157634,  0.21503249],
       [-1.89415691,  0.44697764],
       [ 1.67100423,  1.75166912],
       [-0.30964085, -1.37959044],
       [-0.30964085, -0.65476184],
       [ 0.8787462 ,  2.15757314],
       [ 0.28455268, -0.53878926],
       [ 0.8787462 ,  1.02684052],
       [-1.49802789, -1.20563157],
       [ 1.07681071,  2.07059371],
       [-1.00286662,  0.50496393],
       [-0.90383437,  0.30201192],
       [-0.11157634,

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression()

In [15]:
classifier = LogisticRegression(penalty='l2',solver='lbfgs')
classifier.fit(x_train,y_train)

LogisticRegression()

In [16]:
y_pred = classifier.predict(x_test)

In [17]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [18]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[65  3]
 [ 8 24]]


In [19]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)

0.89


In [20]:
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.89      0.96      0.92        68
           1       0.89      0.75      0.81        32

    accuracy                           0.89       100
   macro avg       0.89      0.85      0.87       100
weighted avg       0.89      0.89      0.89       100



In [21]:
bias = classifier.score(x_train,y_train)
print(bias)

0.8233333333333334


In [22]:
variance = classifier.score(x_test,y_test)
print(variance)

0.89


In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.20, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[57  1]
 [ 5 17]]
0.925
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        58
           1       0.94      0.77      0.85        22

    accuracy                           0.93        80
   macro avg       0.93      0.88      0.90        80
weighted avg       0.93      0.93      0.92        80

0.821875
0.925


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.20, random_state=100)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[46  3]
 [11 20]]
0.825
              precision    recall  f1-score   support

           0       0.81      0.94      0.87        49
           1       0.87      0.65      0.74        31

    accuracy                           0.82        80
   macro avg       0.84      0.79      0.80        80
weighted avg       0.83      0.82      0.82        80

0.853125
0.825


In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.20, random_state=51)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[51  1]
 [ 8 20]]
0.8875
              precision    recall  f1-score   support

           0       0.86      0.98      0.92        52
           1       0.95      0.71      0.82        28

    accuracy                           0.89        80
   macro avg       0.91      0.85      0.87        80
weighted avg       0.90      0.89      0.88        80

0.834375
0.8875


In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.20, random_state=11)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[50  3]
 [11 16]]
0.825
              precision    recall  f1-score   support

           0       0.82      0.94      0.88        53
           1       0.84      0.59      0.70        27

    accuracy                           0.82        80
   macro avg       0.83      0.77      0.79        80
weighted avg       0.83      0.82      0.82        80

0.846875
0.825


In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.20, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)

[[57  1]
 [ 5 17]]
0.925
              precision    recall  f1-score   support

           0       0.92      0.98      0.95        58
           1       0.94      0.77      0.85        22

    accuracy                           0.93        80
   macro avg       0.93      0.88      0.90        80
weighted avg       0.93      0.93      0.92        80

0.821875
0.925


In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y , test_size=0.25, random_state=0)
from sklearn.preprocessing import Normalizer
sc = Normalizer()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
from sklearn.metrics import classification_report
cr = classification_report(y_test, y_pred)
print(cr)
bias = classifier.score(x_train,y_train)
print(bias)
variance = classifier.score(x_test,y_test)
print(variance)
#scaling normalier is low accuracy

[[68  0]
 [32  0]]
0.68
              precision    recall  f1-score   support

           0       0.68      1.00      0.81        68
           1       0.00      0.00      0.00        32

    accuracy                           0.68       100
   macro avg       0.34      0.50      0.40       100
weighted avg       0.46      0.68      0.55       100

0.63
0.68


C:\Users\omkar joshi\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\omkar joshi\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\omkar joshi\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier,

In [29]:
dataset = pd.read_csv(r"C:\Users\omkar joshi\DATA SCIENCE\Databases\final1.csv")
dataset

Unnamed: 0   User ID  Gender  Age  EstimatedSalary
0           0  15724611    Male   45            60000
1           1  15725621  Female   79            64000
2           2  15725622    Male   23            78000
3           3  15720611  Female   34            45000
4           4  15588044    Male   29            76000
5           5  15746039  Female   70            89000
6           6  15704887    Male   86           120000
7           7  15746009  Female   46            23000
8           8  15876009    Male   32            70000
9           9  15886009  Female  100            90000

In [30]:
d2 = dataset.copy()

In [31]:
d2

Unnamed: 0   User ID  Gender  Age  EstimatedSalary
0           0  15724611    Male   45            60000
1           1  15725621  Female   79            64000
2           2  15725622    Male   23            78000
3           3  15720611  Female   34            45000
4           4  15588044    Male   29            76000
5           5  15746039  Female   70            89000
6           6  15704887    Male   86           120000
7           7  15746009  Female   46            23000
8           8  15876009    Male   32            70000
9           9  15886009  Female  100            90000

In [32]:
df1 = dataset.iloc[:,[3,4]].values

In [33]:
df1

array([[    45,  60000],
       [    79,  64000],
       [    23,  78000],
       [    34,  45000],
       [    29,  76000],
       [    70,  89000],
       [    86, 120000],
       [    46,  23000],
       [    32,  70000],
       [   100,  90000]])

In [34]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [35]:
M = sc.fit_transform(x, dataset)

In [36]:
y_pred1 = pd.DataFrame(M)

In [37]:
d2 = pd.DataFrame(M)   # or df1 if that’s your original data
d2['y_pred1'] = classifier.predict(M)

In [38]:
d2.to_csv("final.csv")
import os 
os.getcwd()

'c:\\Users\\omkar joshi\\DATA SCIENCE\\jupyterNotebook'

In [39]:
from sklearn.svm import SVC
classifier_svm = SVC()
classifier_svm.fit(x_train, y_train)

SVC()

In [40]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[68  0]
 [32  0]]


In [41]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)


0.68


In [45]:
classifier_svm = SVC(C=1,kernel='poly',degree=4,gamma='auto')
classifier_svm.fit(x_train, y_train)
cm = confusion_matrix(y_test, y_pred)
print(cm)
ac = accuracy_score(y_test, y_pred)
print(ac)


[[68  0]
 [32  0]]
0.68
